backend:
  name: 'git-gateway'
  branch: 'develop'
  accept_roles:
    - 'admin'
    - 'editor'

media_folder: static/images
public_folder: /images

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - { name: 'type', label: 'Type', widget: 'hidden', default: 'blog' }
      - { name: 'date', label: 'Date', widget: 'date', default: '', format: 'DD.MM.YYYY' }
      - { name: 'title', label: 'Title' }
      - { name: 'body', label: 'Body', widget: 'markdown' }

  - name: 'events'
    label: 'Events'
    folder: 'src/pages/events'
    create: true
    slug: 'events/{{slug}}'
    fields:
      - { name: 'type', label: 'Type', widget: 'hidden', default: 'event' }
      - { name: 'date', label: 'Date', widget: 'date', default: '', format: 'DD.MM.YYYY' }
      - { name: 'image', label: 'Image', widget: 'image' }
      - { name: 'title', label: 'Title' }
      - { name: 'body', label: 'Body', widget: 'markdown' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Homepage'
        name: 'index'
        delete: false
        fields:
          - { label: 'Type', name: 'type', widget: 'hidden', default: 'index' }
          - label: 'Hero'
            name: 'hero'
            widget: 'object'
            fields:
              - { name: 'image', label: 'Image', widget: 'image' }
              - { name: 'headline', label: 'Headline', widget: 'text' }
          - label: 'Vibes'
            name: 'vibes'
            widget: 'object'
            fields:
              - {
                  label: 'Gallery',
                  name: 'gallery',
                  widget: 'list',
                  field: { label: Image, name: image, widget: image },
                }
          - label: 'Bar'
            name: 'bar'
            widget: 'object'
            fields:
              - { label: 'Description', name: 'description', widget: 'text' }
          - label: 'Contact'
            name: 'contact'
            widget: 'object'
            fields:
              - { label: 'Opening Hours', name: 'openingHours', widget: 'text' }
              - { label: 'Route', name: 'route', widget: 'text' }
              - { label: 'Contact', name: 'contact', widget: 'text' }

  - name: 'settings'
    label: 'Settings'
    files:
      - file: 'src/pages/settings/general.md'
        label: 'General'
        name: 'general'
        delete: false
        fields:
          - { label: 'Type', name: 'type', widget: 'hidden', default: 'general' }
          - label: 'Globals'
            name: 'globals'
            widget: 'object'
            fields:
              - {
                  label: 'Title*',
                  name: 'title',
                  widget: 'string',
                  hint: 'Title of the website',
                  required: true,
                }
              - { label: 'Instagram', name: 'instagram', widget: 'string' }
              - { label: 'Facebook', name: 'facebook', widget: 'string' }

          - label: 'SEO'
            name: 'seo'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string', hint: 'Title for SEO' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - {
                  label: 'Keywords',
                  name: 'keywords',
                  hint: 'Separate keywords with a comma e.g. Bar, Drinks',
                  widget: 'string',
                }
