backend:
  name: 'git-gateway'
  branch: 'develop'
  accept_roles:
    - 'admin'
    - 'editor'

media_folder: static/images
public_folder: /images

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Homepage'
        name: 'index'
        delete: false
        fields:
          - { label: 'Type', name: 'type', widget: 'hidden', default: 'index' }
          - label: 'Vibes'
            name: 'vibes'
            widget: 'object'
            fields:
              - {
                  label: 'Gallery',
                  name: 'gallery',
                  widget: 'list',
                  field: { label: Image, name: image, widget: image },
                }
          - label: 'Bar'
            name: 'bar'
            widget: 'object'
            fields:
              - { label: 'Headline', name: 'headline', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
          - label: 'Route'
            name: 'route'
            widget: 'object'
            fields:
              - { label: 'Headline', name: 'headline', widget: 'string' }
              - {
                  label: 'Text',
                  name: 'text',
                  widget: 'text',
                  hint: 'For a line-break insert <br>',
                }
              - { label: 'URL', name: 'url', widget: 'string', hint: 'Google Maps url' }
          - label: 'Opening hours'
            name: 'openingHours'
            widget: 'object'
            fields:
              - { label: 'Headline', name: 'headline', widget: 'string' }
              - {
                  label: 'Text',
                  name: 'text',
                  widget: 'text',
                  hint: 'For a line-break insert <br>',
                }
          - label: 'Reservation'
            name: 'reservation'
            widget: 'object'
            fields:
              - { label: 'Headline', name: 'headline', widget: 'string' }
              - {
                  label: 'Text',
                  name: 'text',
                  widget: 'text',
                  hint: 'For a line-break insert <br>',
                }

      - file: 'src/pages/impressum.md'
        label: 'Impressum'
        name: 'impressum'
        delete: false
        fields:
          - { name: 'type', label: 'Type', widget: 'hidden', default: 'static' }
          - { name: 'headline', label: 'Headline' }
          - { name: 'body', label: 'Body', widget: 'markdown' }

      - file: 'src/pages/datenschutz.md'
        label: 'Datenschutz'
        name: 'datenschutz'
        delete: false
        fields:
          - { name: 'type', label: 'Type', widget: 'hidden', default: 'static' }
          - { name: 'headline', label: 'Headline' }
          - { name: 'body', label: 'Body', widget: 'markdown' }

  - name: 'settings'
    label: 'Settings'
    files:
      - file: 'src/pages/settings/general.md'
        label: 'General'
        name: 'general'
        delete: false
        fields:
          - { label: 'Type', name: 'type', widget: 'hidden', default: 'general' }
          - label: 'Globals'
            name: 'globals'
            widget: 'object'
            fields:
              - {
                  label: 'Title*',
                  name: 'title',
                  widget: 'string',
                  hint: 'Title of the website',
                  required: true,
                }

          - label: 'SEO'
            name: 'seo'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string', hint: 'Title for SEO' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - {
                  label: 'Keywords',
                  name: 'keywords',
                  hint: 'Separate keywords with a comma e.g. Bar, Drinks',
                  widget: 'string',
                }
