backend:
  name: 'git-gateway'
  branch: 'develop'
  accept_roles:
    - 'admin'
    - 'editor'

media_folder: 'static/assets'
public_folder: 'assets'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - { name: 'type', label: 'Type', widget: 'hidden', default: 'blog' }
      - { name: 'date', label: 'Date', widget: 'date' }
      - { name: 'title', label: 'Title' }
      - { name: 'body', label: 'Body', widget: 'markdown' }

  - name: 'events'
    label: 'Events'
    folder: 'src/pages/events'
    create: true
    slug: 'events/{{slug}}'
    fields:
      - { name: 'type', label: 'Type', widget: 'hidden', default: 'event' }
      - { name: 'date', label: 'Date', widget: 'date', default: '', format: 'DD MM YYYY' }
      - { name: 'title', label: 'Title' }
      - { name: 'body', label: 'Body', widget: 'markdown' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Homepage'
        name: 'index'
        delete: false
        fields:
          - { label: 'Type', name: 'type', widget: 'hidden', default: 'index' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Headline', name: 'headline', widget: 'string' }
          - { label: 'Subline', name: 'subline', widget: 'string' }

  - name: 'settings'
    label: 'Settings'
    files:
      - file: 'src/pages/settings/seo.md'
        label: 'SEO'
        name: 'seo'
        delete: false
        fields:
          - { label: 'Type', name: 'type', widget: 'hidden', default: 'settings' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - {
              label: 'Keywords',
              name: 'keywords',
              hint: 'Separate keywords with a comma',
              widget: 'string',
            }
