backend:
  name: git-gateway
  branch: develop
  accept_roles:
    - admin
    - editor

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: data/blog
    create: true
    slug: '{{slug}}'
    fields:
      - { name: 'type', label: 'Type', widget: 'hidden', default: 'blog' }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: events
    label: Events
    folder: data/events
    create: true
    slug: 'events/{{slug}}'
    fields:
      - { name: 'type', label: 'Type', widget: 'hidden', default: 'event' }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'data/index.md'
        label: 'Homepage'
        name: 'index'
        fields:
          - { label: 'Type', name: 'type', widget: 'hidden', default: 'index' }
          - { label: Title, name: title, widget: string }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
